name: CI - Python Flask

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes básicos
        run: |
          python -m unittest discover -s test -p "*.py"

      # Enviar alerta no Telegram (sempre executa, sucesso ou falha)
      - name: Enviar alerta no Telegram
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="Build e testes passaram com sucesso!"
          else
            STATUS="Falha no build ou nos testes!"
          fi
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="🚀 *GitHub Actions* - CI Pipeline
          Repositório: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Autor: ${{ github.actor }}
          Status: $STATUS" \
            -d parse_mode="Markdown"
