name: CI - Python Flask

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          python -m unittest discover

      # Enviar alerta no Telegram (sempre executa, sucesso ou falha)
      - name: Enviar alerta no Telegram
        if: always()
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" = "success" ]; then
            MSG=" Build e testes passaram com sucesso!"
          else
            MSG=" Falha no build ou nos testes!"
          fi
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="*GitHub Actions* - CI Pipeline\nRepositório: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nAutor: ${{ github.actor }}\nStatus: $MSG" \
            -d parse_mode="Markdown"
